name: Build PDF
permissions: write-all

on:
  # Run pipeline every first day of the month
  schedule:
    - cron: '0 0 1 * *'
  # Run Pipeline on Manual Push
  push:
    branches:
    - main

jobs:
  publish_pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Create PDF file from GitHub pages
      uses: misaelnieto/web_to_pdf_action@master
      with:
        webPageURL: https://doctor500.github.io/cv/
        outputFile: cv.pdf
        usePuppeteer: true
        pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name: Publish pipeline artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv.pdf
        path: cv.pdf
    - name: Setup for cron pipeline
      if: ${{github.event_name == 'schedule'}}
      run: echo "PREFIX_FILE_NAME=SCHEDULE" >> $GITHUB_ENV
    - name: Setup for manual trigger pipeline
      if: ${{github.event_name != 'schedule'}}
      run: echo "PREFIX_FILE_NAME=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMM
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PIPELINE_YEARDATE: "${{ steps.current-time.outputs.formattedTime }}"
      with:
        tag_name: "CV-${{ env.PIPELINE_YEARDATE }}-${{ env.PREFIX_FILE_NAME }}"
        release_name: "CV-${{ env.PIPELINE_YEARDATE }}-${{ env.PREFIX_FILE_NAME }}"
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PIPELINE_YEARDATE: "${{ steps.current-time.outputs.formattedTime }}"
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cv.pdf
        asset_name: "CV-${{ env.PIPELINE_YEARDATE }}-${{ env.PREFIX_FILE_NAME }}.pdf"
        asset_content_type: application/pdf