name: Build PDF
permissions: write-all

on:
  # Manual Trigger
  workflow_dispatch:
  # Run pipeline every first day of the month
  schedule:
    - cron: '0 0 1 * *'
  # # Run Pipeline on Manual Push
  # push:
  #   branches:
  #   - main

jobs:
  build_jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1.0.6
      with:
        source: ./
        destination: ./_site
    - name: Publish pipeline artifact
      uses: actions/upload-artifact@v3
      with:
        name: jekyll-page
        path: ./_site

  publish_pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Setup for scheduled pipeline
      if: ${{ github.event_name == 'schedule' }}
      run: |
        echo "RELEASE_TYPE=Scheduled" >> $GITHUB_ENV
        echo "RELEASE_DESC=Monthly release for CV" >> $GITHUB_ENV
    - name: Setup for manual trigger pipeline
      if: ${{ github.event_name != 'schedule' }}
      run: |
        echo "RELEASE_TYPE=Manual" >> $GITHUB_ENV
        echo "RELEASE_DESC=on-demand release (generated manually)" >> $GITHUB_ENV
    - name: Get current date
      run: |
        echo "PIPELINE_TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
        echo "PIPELINE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "PIPELINE_YEAR=$(date +'%Y')" >> $GITHUB_ENV
        echo "PIPELINE_MONTH=$(date +'%B')" >> $GITHUB_ENV
    # - name: Create PDF file from GitHub pages
    #   id: create_pdf
    #   uses: misaelnieto/web_to_pdf_action@v0.3.1
    #   with:
    #     webPageURL: https://doctor500.github.io/cv/
    #     outputFile: "CV_David Layardi_${{ env.PIPELINE_DATE }}.pdf"
    #     usePuppeteer: true
    #     # pdfOptions: '{"format": "Letter", "margin": {"top": "3cm", "left": "3cm", "right": "3cm", "bottom": "3cm"}}'
    # - name: Publish pipeline artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: "CV_David Layardi_${{ env.PIPELINE_DATE }}.pdf"
    #     path: "CV_David Layardi_${{ env.PIPELINE_DATE }}.pdf"
    #temp
    # - name: Create Release
    #   id: create_release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: "CV_David Layardi_${{ env.PIPELINE_DATE }}.pdf"
    #     fail_on_unmatched_files: true
    #     name: "🚀 ${{ env.RELEASE_TYPE }} release ${{ env.PIPELINE_MONTH }} ${{ env.PIPELINE_YEAR }}"
    #     tag_name: "${{ env.PIPELINE_YEAR }}-${{ env.RELEASE_TYPE }}-${{ env.PIPELINE_TIMESTAMP }}"
    #     body: "${{ env.RELEASE_DESC }} "
