name: Build PDF

on:
  # Run pipeline every first day of the month
  schedule:
    - cron: '0 0 1 * *'
  # Run Pipeline on Manual Push
  push:
    branches:
    - master
    #temp
    - feat/pdf-pipeline

jobs:
  publish_pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Create PDF file from GitHub pages
      uses: misaelnieto/web_to_pdf_action@master
      with:
        webPageURL: https://doctor500.github.io/cv/
        outputFile: cv.pdf
        usePuppeteer: true
        pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name: Publish pipeline artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv.pdf
        path: cv.pdf
  create_release:
    runs-on: ubuntu-latest
    needs: publish_pdf
    steps:
    - name: Setup Custom variable
      run: |
        if "${{github.event_name}}" == "schedule":
          echo "PREFIX_FILE_NAME=SCHEDULE" >> $GITHUB_ENV
        else:
          echo "PREFIX_FILE_NAME=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "CV-${{ env.PREFIX_FILE_NAME }}-${{ env.GITHUB_RUN_MONTH }}-${{ env.GITHUB_RUN_YEAR }}"
        release_name: "CV-${{ env.PREFIX_FILE_NAME }}-${{ env.GITHUB_RUN_MONTH }}-${{ env.GITHUB_RUN_YEAR }}"
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cv.pdf
        asset_name: cv.pdf
        asset_content_type: application/pdf